Run cargo update unconditionally
Rust 1.40.0 fails to install due to 

```
error: failed to select a version for the requirement `addr2line = "= 0.24.2"`
  candidate versions found which didn't match: 0.22.0, 0.21.0, 0.20.0, ...
  location searched: crates.io index
required by package `backtrace v0.3.74`
    ... which is depended on by `tokio v1.40.0`
    ... which is depended on by `fs-err v2.11.0 (/home/runner/work/fs-err/fs-err)`
```

The addr2line 0.24.2 library targets 1.65 as the minimum version https://crates.io/crates/addr2line/0.24.2 which is below 1.40.

Calling `cargo update` unconditionally will re-resolve the dependencies, allowing cargo to find a version of addr2line that satisfies version dependencies.