Update the minimum supported version to 1.65.0
Rust 1.40 does not support "weak dep features"

```
$ cargo +1.49 test
error: failed to parse manifest at `/Users/rschneeman/Documents/projects/fs-err/Cargo.toml`

Caused by:
  optional dependency features with `?` syntax are only allowed on the nightly channel and requires the `-Z weak-dep-features` flag on the command line
  Feature `debug` had feature value `tokio?/rt-multi-thread`.
```

The tests use `tempfile` which requires `oncecell` which has a minimum of 1.65+.

By updating to this minimum Rust version we can test file operations and their associated outputs in CI and remove the old 1.63 checks. However, the `debug` feature is still limited to 1.79+.