Update test rust version
```
Run actions-rs/cargo@v1
  with:
    command: test
    use-cross: false
  env:
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
/home/runner/.cargo/bin/cargo test
 Downloading crates ...
  Downloaded serde_json v1.0.129
error: failed to parse manifest at `/home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/serde_json-1.0.129/Cargo.toml`
Caused by:
  failed to parse the `edition` key
Caused by:
  supported edition values are `2015` or `2018`, but `2021` is unknown
```

From https://www.reddit.com/r/rust/comments/sjoht3/receiving_error_supported_edition_values_are_2015/ `2021` was added in 1.56.0